spring:
    application:
      name: twitter-challenge
    data:
      cassandra:
        keyspace-name: twitter_keyspace
        local-datacenter: datacenter1
        schema-action: RECREATE_DROP_UNUSED
        contact-points: ${SPRING_DATA_CASSANDRA_CONTACT_POINTS}
        port: 9042
        connect-timeout-millis: 10000ms
        read-timeout-millis: 10000ms
        connect-timeout: 10000ms
        read-timeout: 10000ms
        pool.pool-timeout: 10000ms

